### ISSUE TITLE
Scoring System

### ISSUE THREAD

**Issue by patelneel55** [epituch/Translate-Game#5]
Scoring the translation process:
- Use the Damerau-Levenstein algorithm to evaluate string similarity (referenced in https://softwareengineering.stackexchange.com/questions/330934/what-algorithm-would-you-best-use-for-string-similarity)
- Weight languages supported by Google Translate.
    - Languages that have hard translations/ direct translations have lower weightage

**Comment by rsirosh** [comment]
Potential for weights of languages:
https://docs.google.com/spreadsheets/d/1fJQLMj8O5z3Q7eKDxi1tNNrFipiEL0UDyaEF0fleZ54/edit#gid=0

**Comment by patelneel55** [comment]
This is a pretty cool list....I'll try adding it to the server
